/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { User, Project, Comment, Topic } from "./types";

export const initialUsers: Record<string, User> = {
  alexchen: {
    id: "alexchen",
    name: "Alex Chen",
    role: "Systems Architect & Designer",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuB7VY3FYBeeddOHqhxygbCsJKwFPFXrcXLYbenUI1AtfHvMo0MSUbY6D1NKeJErwAumEF-I7a3SjrJlxofG2340W6kIMlesfCZpHB3Bl_4qTitwzMWW2sEIg88h830N261aLEXsKrAEIeI6XztDk3qoK8tq4Lqa2tnwEmUQb9NPfs2ivzYyefDt-R84NePo3NWn7i_7VsibMVLFr_v6oTqlG5a220YNfxaMSwi1RDVpYq_dv5D15buSk0ZJWG52xJywl5tmYgxJEB6T",
    bio: "Multi-disciplinary designer and systems architect exploring the intersection of generative AI and sustainable urban planning. Building tools for the next generation of creators.",
    stats: {
      innovations: 24,
      collabs: 158,
      followers: "4.2k",
    },
  },
  alexrivera: {
    id: "alexrivera",
    name: "Alex Rivera",
    role: "Innovation Lead",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAguWnS_mf2wJTa8Qh4E7ME6LSP2PsrAZdULlWDyV1FHidVmdctGbIqKaaObfhO4cnkokf7gmGDzjUxQeXML8HPdHqHKNRu7VFSG8pA_mVt4yelT49DICUzHXW73SVZTghMG4MHpPsHuGvt_j8D4REAxeOHAv1azEoWISxGnEIaT0ULqsPk3rOp1KxvrVObbhLLYkZxGYXXTn7Mp8bR5z7Oc8s7cIDBStfdrabDtBiO_Ulcl_TSflm9uLv0hBku0v3ahdKssJH86M3U",
    bio: "Lead researcher at Earth Tech Labs. Developing bio-mimetic materials and low-footprint compute cooling modules for zero-carbon environments.",
    stats: {
      innovations: 8,
      collabs: 42,
      followers: "1.8k",
    },
  },
  mayachen: {
    id: "mayachen",
    name: "Maya Chen",
    role: "Creative Technologist",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAmG4p649uYikUvT73w8caZkgOwxuATWcpMOcbhl9RwdnS7joae0CXkFCZWJae2Iwi-ldoD6pRVFmtEVgZUSUnDGfnDpGnm2VTA2nOWlIP93BUH3Iyafavj1IHZ8dbfJJFVuXXFgf3xXpnJ-YO0_MENbAgnGMNsNnDdBmx3eoW8Yxm49kL_HWSJHfMsJmzs-RIWYha9SlBPrBAxvTSALtKmKfxaghrFaQN3GvYUqLVgcDu1SNrsAMhrfYIsK8D94VDR-U54WJWcRkar",
    bio: "Crafting physical interfaces and tactile compute devices that translate complex signals into tangible physical sensations.",
    stats: {
      innovations: 14,
      collabs: 93,
      followers: "3.1k",
    },
  },
  julianrivers: {
    id: "julianrivers",
    name: "Julian Rivers",
    role: "Lead Designer",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAvszxZs02p_bbtgSIXxjTBarVmbqWywQQ7UynfuqzLDKC1GpzBlRCC26Kr9COIB9v6nFHZibL2Tg18IhNibJ2xJc6xC6RvAt4fxYReDuUip81viGWPXuQCj8neNzBJ9OdLVZx9jssVY1byTDlgZJJgeypFA1b0-pQTo5V1_LLTpcqxOfX4o3DAccsAoKjEpW97T5YzQzJXzSeC8fw6_N2U2IUoHrc1QJP9y8OzAuwvr-FsbFLUo5lDA4ZR92P7yg0cBRAek-ukEa-V",
    bio: "Landscape architect exploring environmental restoration through user interface structures and IoT node design.",
    stats: {
      innovations: 12,
      collabs: 78,
      followers: "2.5k",
    },
  },
  sarahjenkins: {
    id: "sarahjenkins",
    name: "Sarah Jenkins",
    role: "Workspace Strategist",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuC6qzwCXkQf7haJrHHjNiVALQJPfTf20mTpBFSkBridztaCu_HkMFgS8W9J2QzrxG4SpWlqxd483QXhAHL098NkGNN1ovh_mujiuJmT6EBTpr4_unaq_U4eos39M6-liO-FVzPC3lPnxfij9WU9t6Q-k3HNkmTS78_1gIiDd33GpK9aYm5b0bouN7hPbKWUPxSANJWBFIPxJMoJGjdgxisoviRQUOrDD-B6RtiJ8PuUt5FRGmvH1aTFQTr1mgo7i0O15hauhOhasnov",
    bio: "Focused on human-centered design for corporate campuses and distributed worker systems.",
    stats: {
      innovations: 5,
      collabs: 29,
      followers: "920",
    },
  },
  mariavelez: {
    id: "mariavelez",
    name: "Maria Velez",
    role: "Interface Scientist",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAvxs3qG8asY-C79DPxmBDMtg3iOOicI1S2u8hMsX8E2337cnXZfS-esPMoQXcHYa5_5GMCBIRfVKd5z72pCFtHh5eMHEyF2zcVw1oXuOq7ib3vThRK4hluzlMSn_g5VDdJkROF81NkZH846NOv27PjdTSCmd3QKqWYqqnAENpnKKs7K9HByG9Oi-69gIm4s6KpU7Ex7MtUzfhdy5i1aR58_LNrclfLpzoHsorHQPT-1wM1r8ILwqK4QCh9OLJOX5QGPJ8nRPkNbNpW",
    bio: "Architecting atomic geometry styles and modular layout patterns for next gen systems.",
    stats: {
      innovations: 11,
      collabs: 65,
      followers: "1.1k",
    },
  },
};

export const initialProjects: Project[] = [
  {
    id: "neo-city",
    title: "Neo-City Modular Systems",
    description: "A comprehensive design system for parametric urban environments, focusing on dynamic asset allocation and aesthetic cohesion.",
    category: "UI Design",
    authorId: "alexchen",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuALd7K46843AN8XVhQud2eAgGopaQiAjUhvOUhyxXgWOk4hSTf6ugAouqnQ6H0SSs3ntNzQ35PQR92ELzLjG3G-JtnrXoOBMAfNKMljio5fAdaxVm8w6fDlpuaq_zZznjhIsluOpFd81P-oF672v-HJSnh63qUpiXGIVOwFQ9Ctl4onlKFM-afOHjwTJHXfoosvbBZTcAMl-xtLdc6bpukzW9TBf2YnyVQb9c619eL1ZDAfDlnZlh_th8uTETWiDIcL6wJJMU5UcsSt",
    likes: 842,
    commentCount: 46,
    isLiked: false,
    tags: ["UI Design", "Procedural Grid", "Urban Planning", "Three.js"],
    vision: "Parametric urban assets that react to human traffic densities in real time, organizing modular landscapes recursively. The design language fuses Brutalism with vertical foliage, and is optimized for low-latency web browser rendering.",
    goals: [
      "Procedural foliage allocation in geometric structures.",
      "Vaporization nodes for sustainable heat dispersion.",
      "Responsive layout for grid customization sandbox.",
    ],
    relatedProjects: ["quantum-ux", "smart-workspace"],
  },
  {
    id: "quantum-ux",
    title: "Quantum UX Patterns",
    description: "Defining how users interact with multi-state logic and probability dashboards in quantum systems.",
    category: "Research",
    authorId: "alexchen",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDH-0wT3qfxPj45CTc0EVcQ122YD4zaZHVKj8hlohn0S-ytTRk_0_zVI8PciyaxM2MWo3Nkz0ilL6rWsGIZijn2H3cMNQdX-hTDEGZ37m7pn6IyMBZl9T4gPsikqTO77XFszh3UhXbKt31eR-rGN3YPlH2iHAEwDcZlZAU6Px0waj-n-x1uv3MoCrDvqJ80ezIttjHwrr9bZ1U8Zc_8dGUdL5hQ6V_Ua3qp40L25qmkKNbt9bPUJ-U7dstVnpw5D7uGdZfr-5UGgvzS",
    likes: 312,
    commentCount: 9,
    isLiked: false,
    tags: ["Research", "Quantum Design", "Probability UI"],
    vision: "Designing intuitive interfaces that visually grasp simultaneous qubit states. Eliminating classical state switches for real-time wave functions modeling interfaces.",
    goals: [
      "Co-exist state overlapping transitions rendering.",
      "Entanglement visual link lines representation.",
      "Phase mapping colors directly synced with hardware responses.",
    ],
    relatedProjects: ["neural-hub", "aether-core"],
  },
  {
    id: "aether-core",
    title: "Aether Core V2",
    description: "Redesigning the central processing unit and architectural routing layouts for decentralized node physical layers.",
    category: "Hardware",
    authorId: "alexchen",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBFPjURpY2havi0PM8q1RqsBHeh_2mdTfDTyyRcuv-fVIOeOMX9Ov0cRhHZ5nVSibuH-yn_rYcrPeJSAw813NejN8WXs1INH2hY-zYriSFfdSkQgRzq1iVOxeMxAxqYkhKawepXZpd6NAP3aU4uLRdRyzLuRM8_GruK-1sFVS9nyp_7u6JIA0ITJfT0gsdSXsXFxMUoEzC3etyFmOFtTOT2F-BKEq58eH3a1TCylMEzRH75tNGvWKu4oVG8cd9AO6lejKk3bAcu6HrN",
    likes: 529,
    commentCount: 15,
    isLiked: false,
    tags: ["Hardware", "Decentralized Nodes", "Material Science"],
    vision: "Decentralized data node architecture layered inside heat-convective aluminum-silicon sleeves. Thermal conduction routes double as bus signals, rendering active diagnostics externally via luminescent nodes.",
    goals: [
      "93% thermal conduction efficiency target.",
      "Integrated analog physical clock lights.",
      "Direct stackable expansion bracket slots.",
    ],
    relatedProjects: ["neural-mesh"],
  },
  {
    id: "bias-mitigation",
    title: "Bias Mitigation Framework",
    description: "A whitepaper on algorithmic fairness in credit scoring and machine learning resource allocation.",
    category: "Ethics",
    authorId: "alexchen",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDTZWEC_egLvp_7CYZYdVhsx-iMk4XcQ5BSAwPVNSSe8uf7mzjvrrEiNwIeCWluY6rEh2MtPDpjtvo-cP91CWzDTXF6h-_dXT4imsZXr0ZPzgDTy-8_TMGwHIs2ZCRiTHCQvMeKRj1_L_0CRyaZs6Pd6vC6Bd6L0fmSEZciscxSdNEmJ-k9AcnzwpWQW-1g1RuUc1sGFAeKdZqySLuyhrHGwKjcanCVPV66wpt6pyl9VFrjXnkOKiZUdgB9CBOlgt_G_Mi5rGFqMuYH",
    likes: 1210,
    commentCount: 38,
    isLiked: false,
    tags: ["Ethics", "AI Fairness", "Decentralized Tech"],
    vision: "Providing transparent and auditable metrics for loan processing neural models to ensure geographic and gender equality.",
    goals: [
      "Model drift automated alert loops.",
      "Visual equity dashboard layers representing variance.",
      "Immutable ledger logging for fairness scoring.",
    ],
    relatedProjects: ["quantum-ux"],
  },
  {
    id: "lumina-identity",
    title: "Lumina Identity System",
    description: "Visual brand language and asset design for a high-end renewable tidal energy startup.",
    category: "Branding",
    authorId: "alexchen",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDKWqmDdQ0ZOwFaM3gt6cuBgfs49gZg6MHUCEAVHIbTAd5x16fIm481CTkHMlFAWV9eYVe2vTNANFTr-ykqAk0Qztx9D5E9To2HcQBvDYSWqSXfR3scO7XUZym_eNt6fJtfXfWL0K0FU7PNxI-y7zmn6uidEo3nxgQ87ZxbnZ3t3jGlRcIKAyNi59B2TicTYKfcSciUA0rq_d-I18eRyB6TetZbE8ZmbVv4OUIH-eiWPE6KQR6h1TpJ2RRO3J-xUkjaAKLr3UHwIppm",
    likes: 245,
    commentCount: 4,
    isLiked: false,
    tags: ["Branding", "Identity System", "Marketing Slate"],
    vision: "A deeply elegant visual brand identity showcasing the flow and strength of marine deep currents.",
    goals: [
      "Harmonic logotype structured strictly on golden spirals.",
      "Eco-ink certified physical asset paper stock specification.",
      "Open-source modular brand guide accessible via browser.",
    ],
    relatedProjects: ["eco-connect"],
  },
  {
    id: "neural-mesh",
    title: "Neural Mesh - Sustainable Urban Cooling",
    description: "Implementing a bio-mimetic structure designed to reduce city temperatures through passive evaporative cooling. This prototype uses 3D-printed ceramic recycled from industrial waste.",
    category: "Sustainability",
    authorId: "alexrivera",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA7SDJbRXSk_DzriWYtUB7ZF6d0oMffyPiP7FMB2kohGZeWokHufZuJeNZmQRc6O1zww6xq6XiBq2q4PHzd_luUAwCBQpzYZyS2YtPk_3BBMi2rx0LIheWvIXPqIVcqBmQNyoMaXRD5GxW4ovXmIGPUsMt279GgbvJUvUMIPqnLWKSKyVxBBvCbkObTCVStkT0tqbmbahKARAUdsKAJNCZGUkmN_IaTdixsDnjVKKXikPAF0Gkg6UriHz4U_aITH3CRJiHN8jx04bJt",
    likes: 248,
    commentCount: 14,
    isLiked: false,
    tags: ["Sustainability", "Evaporative Cooling", "3D Ceramic"],
    vision: "A system of porous ceramic blocks mimicking respiratory geometries. When saturated with recycled storm runoff, thermal winds invoke active cooling without drawing electrical supply.",
    goals: [
      "Decrease localized facade temperatures by up to 6.2°C.",
      "Formulate low-shrink recycled sludge clay blend for precise firing.",
      "Integrate capillary tubes for regulated moisture level feeds.",
    ],
    relatedProjects: ["eco-connect", "aether-core"],
  },
  {
    id: "echo-interface",
    title: "Echo - Adaptive Music Interface",
    description: "Exploring how haptic feedback can translate complex melodies for hearing-impaired musicians. The glove uses vibrating actuators mapped to pitch and timbre.",
    category: "React Native",
    authorId: "mayachen",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBcThkWFKXQvxTRnBxr3D2ME6uimfcPkgl3KNaZuu3g17anhtuZ7rC4FPkD5cWJQU0LWHvO7GPgLSH1CWSZpJ-eOWRjCUYrfcmg-eMtBBtKNVJJQdE4-Xby_afB03hi3VJU0wF0CnNNqpEfoKN1x4MvJvxvWpgbE10IBjT6daYKezWChxkdc9M4LsAF9QCy-Ny8Ftl9qod6yFT8P_yFvqLOoz-hC5AImFy-vpPdIj6GLdbCe9t0TMpFEkemJd_bqRThnOZEKl5uGNVO",
    likes: 892,
    commentCount: 45,
    isLiked: false,
    tags: ["React Native", "Haptics", "Assistive Tech", "Sensory Translation"],
    vision: "Constructing haptic arrays mapped to audio harmonics in real-time. This project explores glove-based feedback structures allowing deaf musicians to perceive complex musical arrangements dynamically.",
    goals: [
      "Low latency bluetooth connection below 8ms.",
      "Actuator coordinate maps mirroring spatial pitch frequency values.",
      "Dynamic responsive feedback intensity matched to audio envelopes.",
    ],
    relatedProjects: ["quantum-ux", "neural-hub"],
  },
  {
    id: "eco-connect",
    title: "Eco-Connect: Urban Re-wilding Platform",
    description: "Eco-Connect is a collaborative platform designed to bridge the gap between urban planning and environmental restoration.",
    category: "Sustainability",
    authorId: "julianrivers",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBtbIl2WbHOIwgCj3PfLT-zD-EDZg5H-z42aNnk1Gw7wxfP5i6x0yKiq3KJ5HCXqFJSARpckAdxb8aA8kNtXtr8qhfRnFrO8vOrW5JgG-yN9rM686RbdmXmcgOfgd1Nb2vWG0J7rg74YDk1SBII49vaFEjxwYHyoRIZTxbkr58836sWunmiIhc_KLbriiz9-loTLtUWchAayNp_sk41iX_CQXDLXSw4wQtgwh__k9IAURPYrOQWqADw4ATX_A17YpwNbO2ad8CADjPO",
    likes: 1200,
    commentCount: 84,
    isLiked: true,
    tags: ["React Native", "Three.js", "Google Maps API", "Cloud Firestore", "UI Design"],
    vision: "Our mission was to create an interactive interface where architects, ecologists, and local communities can co-create green corridors in dense urban environments.",
    goals: [
      "Real-time biodiversity tracking via IoT sensors.",
      "Community voting on local park features.",
      "AR visualization for proposed green structures.",
      "Carbon sequestration reporting for developers.",
    ],
    relatedProjects: ["smart-workspace", "neural-hub", "modular-design"],
  },
  {
    id: "smart-workspace",
    title: "Smart Workspace Dashboard",
    description: "Innovative corporate office interior with intuitive open spaces and deep indigo and teal custom lighting.",
    category: "Branding",
    authorId: "sarahjenkins",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBd8cygN3HCsRoaRAU9TycRtn0Bv4s2V4PjBIUz04lLM6yAsHNK48TlPn3QgniraU4w9rW49zpWaGPr9MlsXkpy10YrXjhe749fY-riRQParBAlv43D9jR7uIN3r3dzjuEJLSPWnHzLyjCpDi7QvCV30YZ82mEmqFR1qbFCAXC1KNCIBlk06erRqKxKeSlYn5PGtn5l8ViC_32rv72ooZ8m6WYtA_xaN75oWAE0ZcNJ1o8n2fQsogL5edA7Ys3KzIkj0JzJD2SpkmbF",
    likes: 184,
    commentCount: 12,
    isLiked: false,
    tags: ["UI Design", "Industrial Layout"],
  },
  {
    id: "neural-hub",
    title: "Neural Hub Ecosystem",
    description: "Vibrant abstract visualization mapping neural lines in a high-tech machine learning sky environment.",
    category: "Machine Learning",
    authorId: "alexchen",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDC_J6UkeetdkGh18peLQVYO74w0R8phUDA3dSv8xregSza8VQfvsq8pkXyQif0eooX-TpvksJVHTRhKAs6fDDP78iXLhI4XGzFV7POd_R6rszLRRiT1zQAN54n2IM81hVlGUNSZLc_ubQnFY5AabmiRiqzVbilJQ0TcRj3IEOFXxUGDWYs2DXUZ_sueryrFaCfLxHaVFklFhO60w7KDMcvZzXNw6wmV7xBWrQ2izcGwwHtDz_B44_L-2POQMYZM_PxeelbpVZcj8oN",
    likes: 412,
    commentCount: 22,
    isLiked: false,
    tags: ["Machine Learning", "Data Orbit", "Indidgo-Glow"],
  },
  {
    id: "modular-design",
    title: "Modular Design Library",
    description: "A minimalist detailing of white clean concrete showing sharp sunlight shadow plays reflecting corporate layout precision.",
    category: "UI Design",
    authorId: "mariavelez",
    image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDUwQFGuKlKphJcEPP7IgPBk3PSjpqrKba5BUQHvRkDfBwOC2VMvRHrDs89vn58EPUdi5aImHEbdDM3E2P689oxiQSz-EqsLlvVyvP5bdst_Z-cXIpnMkEWslGJ_db94SAQ-3T3ULhKIhJcR8eQF33we-_kRd4prLl4QY_xnrcP0Gy9OlKltWImC_W-xmmp5oW045JOqlSKuWg-_1TsTZ3dLWKrH7qp176r3NdgUF2eb74Ibn_-tWD6m3Juh74rFlrZB5oDBpddtbLM",
    likes: 350,
    commentCount: 11,
    isLiked: false,
    tags: ["UI Design", "Concrete Style", "Precision Geometry"],
  },
];

export const initialComments: Comment[] = [
  {
    id: "comment-1",
    authorName: "Marcus Thorne",
    authorRole: "Senior Dev Lead",
    authorAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAilxINSW0l7WWpynlwjc2rNzJEVGSUGLmbizpdL0FkBX4gjDitZsnUfNLUQ7gXQGOu-zJ38A3QUaXY_FsxmqCjO_AhQmJB3qo_GJAQuSgI6MZ5pM8BWhTFudU_fUKoBThcIMCV4f0Iqxc_0J2nYm7PvfLeZqGLdhbzZp6yuN4XazVj-GXE4pacQdmjBnTOgh1HkeCI7JMkG7aiyMgdtPqU6GlSDrKjCr_7vqwWITJK5qnOeLgDaCWHfTJdbguxHR9JTLPx7DJnBbIC",
    content: "The integration of AR for urban visualization is a game changer. How are you handling the latency for large-scale geometric rendering on mobile devices?",
    timestamp: "2 hours ago",
    likes: 12,
    isLiked: false,
    isAuthor: false,
  },
  {
    id: "comment-2",
    authorName: "Julian Rivers",
    authorRole: "Lead Designer",
    authorAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDtE74ercyWSEsGyKZTarTc7HIbcZQMa8l1Mw3a70MBWVkUqudmuFc1rQsILIErjimjhiU2kbfuBmpk29ADrGTIbkp2Qnses7_bBwDvTJZIdsTBxVzXNk6vzvGVGSmtGnn7rDX6x281x15a83BFs3Iff2R46MugW_YCP149kBOJKc4G2Qq_3u1tg_XsUOihDx83szUixBm614ratDuiFPOHEuRQWyuXr6gHDwr1H4G5F9EDwt82b5uXEtQ0O1zxn1HFiecrhHyVD94X",
    content: "Great question, Marcus! We're using a progressive LOD (Level of Detail) system that streams higher resolution meshes only when the user is within a specific proximity.",
    timestamp: "1 hour ago",
    likes: 4,
    parentId: "comment-1",
    isLiked: false,
    isAuthor: true,
  },
  {
    id: "comment-3",
    authorName: "Elena Rodriguez",
    authorRole: "Urban Ecologist",
    authorAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAsjdhpKngRLmZXttork1jY88_hIdxTWJmojcKGk0B5cgfeO9vlOltkO4yd7cW0W5Li41mi9y-I_t4olW7GNv4e22SiS1aIYpb74yl3VK4llFjVw04RIgKPXHnRh80looUQ2BhC0FsM2AnovVZJVvkwXUeMplCZPpgRO5ijVLjTqVg57-mzWWa1wHfGDYbZ0T-tp5en01rJVXhlpS2XNmL_KuPdNSkFTZHVeBQ128kTxdOaa9O-xdOya6rIpQF6PHibDzIkuhU2D6gn",
    content: "The aesthetic of this platform is incredibly inviting. Usually sustainability tools feel very industrial, but this feels like a space where creativity thrives.",
    timestamp: "5 hours ago",
    likes: 28,
    isLiked: false,
    isAuthor: false,
  },
];

export const initialTrendingTopics: Topic[] = [
  { name: "UI Design", icon: "palette" },
  { name: "React Native", icon: "code" },
  { name: "Machine Learning", icon: "psychology" },
  { name: "Architecture", icon: "architecture" },
  { name: "Sustainability", icon: "eco" },
];
